// Auto-generated from CSV
import { Project, ProjectType } from './types';

export const PROJECTS: Project[] = [
  { id: 1, type: ProjectType.Photo, title: `Alaska Mini Island`, description: `Coastal Alaskan island seen from a boat out of Seward, AK.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Falaska-mini-island.webp?alt=media&token=895e2a40-b4e4-4b08-b631-0f89319edfe8`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Falaska-mini-island.png?alt=media&token=1339e348-864b-4a03-9e07-4a3f23f48b0f`, tags: ["Seward", "image"] },
  { id: 2, type: ProjectType.Photo, title: `Bernal Hill Afternoon`, description: `View westward from the eastern side of Bernal Hill`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-afternoon.webp?alt=media&token=99d81982-8f02-4e00-8cc0-f0494b1caf30`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fbernal-hill-afternoon.png?alt=media&token=fb94a173-9056-4e9e-bedd-529530b95a3d`, tags: ["Bernal Heights Park", "image"] },
  { id: 3, type: ProjectType.Cinemagraph, title: `Fireside Meditation`, description: `#goals to meditate for this long a duration; my back already hurts`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffireside-meditation-cinemagraph.webp?alt=media&token=2f21e360-1697-4e1b-be66-55e3ad0e6e99`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ffireside-meditation-cinemagraph.mp4?alt=media&token=cb88ee30-c924-40a6-bc50-3703377abc29`, tags: ["Stephen", "The Sea Ranch", "cinemagraph"] },
  { id: 4, type: ProjectType.Cinemagraph, title: `The Lost Coast 01`, description: `Two hikers trekking southbound along TLC`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftlc01-cinemagraph.webp?alt=media&token=6287bd4a-6b9e-4d89-bc4b-6359d571ec12`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftlc01-cinemagraph.mp4?alt=media&token=7b11684e-d143-449a-b3dd-f96861fb61c2`, tags: ["Michael", "Lost Coast Trail", "cinemagraph"] },
  { id: 5, type: ProjectType.Cinemagraph, title: `The Lost Coast 02`, description: `Two hikers trekking southbound along TLC`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftlc02-cinemagraph.webp?alt=media&token=d21dbdc6-5068-47f2-b82a-232382cf460e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftlc02_cinemagraph.mp4?alt=media&token=e55de0bd-a08e-4f40-adff-dbd5a0c6ac1d`, tags: ["Michael", "Lost Coast Trail", "cinemagraph"] },
  { id: 6, type: ProjectType.Cinemagraph, title: `The Sea Ranch`, description: `Doesn't get much better than a sunset at TSR`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-sunet-cinemagraph.webp?alt=media&token=e9df3041-85ef-4a42-a366-c51ccdd8db37`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftsr-sunet-cinemagraph.m4v?alt=media&token=6a01df65-976e-4641-b0f9-f89ddce24274`, tags: ["Michael", "The Sea Ranch", "cinemagraph"] },
  { id: 7, type: ProjectType.Cinemagraph, title: `Bernal Hill Sunset`, description: `Sun setting from Bernal Hill in the fall`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-cinemagraph.webp?alt=media&token=e0751aeb-6a81-4f14-afaa-4abb54d1fdc2`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fbernal-hill-sunset-cinemagraph.m4v?alt=media&token=e3d47bce-80aa-4b5b-b3e2-209c5cc2122b`, tags: ["Bernal Heights Park", "cinemagraph"] },
  { id: 8, type: ProjectType.Cinemagraph, title: `Pacifica Coast`, description: `Sun sets behind the best GOBM in the world`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fpacifica-coast-cinemagraph.webp?alt=media&token=6cb3b77e-0ffa-4747-970c-29aca4e7b932`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fpacifica-coast-cinemagraph.mp4?alt=media&token=33ab8ba9-1309-4ec5-a60a-0ca9fcaa29b9`, tags: ["San Pedro Beach", "cinemagraph"] },
  { id: 9, type: ProjectType.Cinemagraph, title: `Bernal Hill Sunrise`, description: `Sun rises over E bay as viewed from Bernal Hils`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunrise-cinemagraph.webp?alt=media&token=3f8e827f-a53d-4f2a-a195-8e2c77c8747a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fbernal-hill-sunrise-cinemagraph.mp4?alt=media&token=f98815bd-4c17-4ef3-9455-7b84cec0ef51`, tags: ["Bernal Heights Park", "cinemagraph"] },
  { id: 10, type: ProjectType.Video, title: `Boulevard of Broken Dreams`, description: `alaska is essential`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fboulevard-of-broken-dreams.webp?alt=media&token=5522c787-eee0-4eb8-ba9c-6b6260683a96`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fboulevard-of-broken-dreams.m4v?alt=media&token=09fcb743-9905-4092-ac93-b4d8003e02ca`, tags: ["Eli", "Denali National Park and Preserve", "video"] },
  { id: 11, type: ProjectType.Video, title: `The Sound of Silence`, description: `#vanlife from SF to Oregon Coast.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fthe-sound-of-silence.webp?alt=media&token=aa535ca5-82f7-459c-8ab1-56425382845d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fthe-sound-of-silence.m4v?alt=media&token=d696d19e-08e9-49c9-b5b6-4880c07e2b33`, tags: ["Michael", "Oregon Coast Range", "video"] },
  { id: 12, type: ProjectType.Video, title: `I Could Be the One`, description: `A bachelor party to remember.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fi-could-be-the-one.webp?alt=media&token=49fc5000-c057-440d-9ced-db44a930df43`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fi-could-be-the-one.m4v?alt=media&token=2f2cd5bb-5416-46a4-8c50-4d9a8db2592f`, tags: ["Eli", "Ayush", "Puerto Vallarta", "video"] },
  { id: 13, type: ProjectType.Video, title: `Second Hand News`, description: `They're back... and they're going big on the big island!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsecond-hand-news.webp?alt=media&token=04b5009a-0dda-400c-8fbb-885ba4086576`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fsecond-hand-news.m4v?alt=media&token=d5adb845-b645-40f6-9e28-7485248ce585`, tags: ["Michael", "Janita", "Tom", "Big Island", "video"] },
  { id: 14, type: ProjectType.Video, title: `No Apagues La Luz`, description: `La vida magnífica.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fno-apagues-la-luz.webp?alt=media&token=b43f9dbb-3e75-45cf-a268-fa573476b7bb`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fno-apagues-la-luz.m4v?alt=media&token=077d6a20-a44b-4c95-9f30-f43d9895d22e`, tags: ["Michael", "Madrid", "video"] },
  { id: 15, type: ProjectType.Video, title: `Winter Song`, description: `A-list crew in an A-frame winter cottage.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fwinter-song.webp?alt=media&token=61682025-d8a4-44fe-b1a7-bf7fad4750b1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fwinter-song.m4v?alt=media&token=c9e676b7-e6c7-4131-a6d5-a28ecf875ca8`, tags: ["Amy", "Irene", "Michael", "Bear Valley", "video"] },
  { id: 16, type: ProjectType.Video, title: `Into the West`, description: `If you found this video on a holiday card -- congratulations... and enjoy!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Finto-the-west.webp?alt=media&token=63b95e54-0d4b-470c-8ee1-8a9d28505a04`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Finto-the-west.m4v?alt=media&token=b3063b82-2c30-4eaa-85f4-43a342204771`, tags: ["Michael", "Big Island", "video"] },
  { id: 17, type: ProjectType.Video, title: `Baba O'Riley`, description: `Tom's debut performance falls short of nothing.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbaba-oriley.webp?alt=media&token=3a0f07ee-505b-4e87-a66f-d92460294e52`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fbaba-oriley.m4v?alt=media&token=861d6db3-779f-423f-b8d4-35ff073ee8d1`, tags: ["Janita", "Tom", "Michael", "Maui", "video"] },
  { id: 18, type: ProjectType.Video, title: `Ojai`, description: `Channel Islands (Santa Cruz Island) + Ojai, CA. Cute island foxes. Lissie.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fojai.webp?alt=media&token=087f0f17-1789-400c-b9d9-3b6ac747b655`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fojai.m4v?alt=media&token=977f3420-5222-48e6-904e-efa4c7f63825`, tags: ["Michael", "Channel Islands", "video"] },
  { id: 19, type: ProjectType.Video, title: `Flightless Bird, American Mouth`, description: `Merrymaking in the Pacific Northwest - North Cascades and British Columbia. September 13 - 19, 2021.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fflightless-bird-american-mouth.webp?alt=media&token=a0405020-b9d9-4013-8bf0-a034aefa93a7`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fflightless-bird-american-mouth.m4v?alt=media&token=7a3989af-86ee-4cd7-817e-4447bc4b6b95`, tags: ["Michael", "Seattle and Vancouver", "video"] },
  { id: 20, type: ProjectType.Video, title: `Cowboy Take Me Away`, description: `New Mexico - Abiquiu Lake, Mesa Verde, Santa Fe. April 25 - 30, 2021.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fcowboy-take-me-away.webp?alt=media&token=a355ccf3-cdb1-4ee0-af85-b11d9d294d11`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fcowboy-take-me-away.m4v?alt=media&token=626a988a-285d-4715-9290-0c066d4add57`, tags: ["Michael", "New Mexico", "video"] },
  { id: 21, type: ProjectType.Video, title: `Rivers and Roads`, description: `Grand Teton & Yellowstone. Sorry for choppy video. As Alanis Morissette says, 'You live, you learn.' August 8 - 14, 2020.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Frivers-and-roads.webp?alt=media&token=475015f3-73ad-4633-9208-b5dbdc148364`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Frivers-and-roads.m4v?alt=media&token=112d58ad-73d9-4f26-a026-4e80b332f4a7`, tags: ["Michael", "Grand Teton National Park and Yellowstone National Park", "video"] },
  { id: 22, type: ProjectType.Video, title: `Shallow`, description: `Arizona antics. Sedona, Grand Canyon, Antelope Canyon. November 9 - 16, 2019.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fshallow.webp?alt=media&token=50221aa1-cd50-41cf-8909-c62fc439b6fb`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fshallow.m4v?alt=media&token=6fe8ec05-fa44-4cd6-ab91-0e2277270c4f`, tags: ["Michael", "Grand Canyon National Park and Sedona", "video"] },
  { id: 23, type: ProjectType.Video, title: `Tiny Dancer`, description: `Janita & Stephen soak up the sun on the beaches of Maui.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftiny-dancer.webp?alt=media&token=5cc67b9b-522e-4ae6-a071-5f3a5907747d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftiny-dancer.m4v?alt=media&token=69e08f35-08f9-44d8-acb2-434eede6285c`, tags: ["Janita", "Maui", "video"] },
  { id: 24, type: ProjectType.Video, title: `Drift Away`, description: `In their debut music video, Emily & Her FBs take advantage of all the Catskills have to offer, and then some...! Catskills 2016`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdrift-away.webp?alt=media&token=6699d24b-c036-4037-a963-b08dbc06cf0b`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fdrift-away.m4v?alt=media&token=0f74b88b-6a93-4c85-ab97-7ae63b9e3d55`, tags: ["Emily", "Jackson", "Michael", "Catskill Mountains", "video"] },
  { id: 25, type: ProjectType.Video, title: `Fly Away Home`, description: `Stephen and Michael fly away home with Mary Chapin Carpenter to Banff & Jasper National Parks, Alberta, Canada. August 13-20, 2016.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffly-away-home.webp?alt=media&token=a34a2b95-e133-48e7-af50-acb9bb65543a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ffly-away-home.m4v?alt=media&token=1e591ef8-d57d-4fc6-b7af-bf8b8109ddaf`, tags: ["Michael", "Banff National Park", "video"] },
  { id: 26, type: ProjectType.Video, title: `Transatlanticism`, description: `Unable to deal with the distance separating them, Michael and Stephen set off on separate journeys to find one another.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftransatlanticism.webp?alt=media&token=c0fc5259-a7b2-43c2-863b-c09ea423ba57`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftransatlanticism.mp4?alt=media&token=e0e342ec-2204-4a70-bad7-5cff8afc694f`, tags: ["Michael", "Iceland", "video"] },
  { id: 27, type: ProjectType.Video, title: `One of Us`, description: `In his debut solo performance, Stephen explores the timeless question: 'What if God was one of us?' Just a stranger on the bus, he travels through Italy and Austria trying to make his way home, with stops in Milan, Innsbruck, Salzburg, and Vienna.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fone-of-us.webp?alt=media&token=dce9f239-8ddc-489c-81e0-446b9e1c758e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fone-of-us.mp4?alt=media&token=ec4c9b7a-9d2e-4691-9b70-4873f2608f39`, tags: ["Stephen", "Austria", "video"] },
  { id: 28, type: ProjectType.Video, title: `Fast Car`, description: `Camping trip to Crater Lake and Redwoods National Park from September 6 - 8, 2013.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffast-car.webp?alt=media&token=f9178a52-29c4-46a1-872a-1da1b3321fca`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ffast-car.mov?alt=media&token=ce20c5b2-47d0-4c79-9745-1c0a18e4ddf3`, tags: ["Michael", "Crater Lake National Park", "video"] },
  { id: 29, type: ProjectType.Video, title: `You Were Meant for Me`, description: `Camping trip to Humboldt State Redwoods State Park from March 20 - 22, 2013.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fyou-were-meant-for-me.webp?alt=media&token=ced56daf-97f0-4c95-9bd7-d99076888748`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fyou-were-meant-for-me.m4v?alt=media&token=1dcfee98-a536-4d69-b1ae-f0c1ef7349e5`, tags: ["Michael", "Humboldt Redwoods State Park", "video"] },
  { id: 30, type: ProjectType.Video, title: `Impossible`, description: `Stephen and Michael are at it once again, this time with an artistic rendition of 'Impossible' from the 1997 classic live-action remake of Cinderella. No rendition of this song could do it justice without also having an 'all-star, multi-racial cast,' as Stephen and Michael bring to the table.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fimpossible.webp?alt=media&token=2d295064-f01c-49b8-bef3-cd9a5b84abb1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fimpossible.mov?alt=media&token=a3b132dc-0770-4000-8105-fac319353f2a`, tags: ["Michael", "Oak Creek Apartments | Stanford", "video"] },
  { id: 31, type: ProjectType.Video, title: `TiK ToK`, description: `Mostly snorkel trip with Michael, Irene, and Stephen. Guest cameo from Janita!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftik-tok.webp?alt=media&token=7477d1bc-536d-4f53-976f-45d93b2d47a3`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fthe-sound-of-silence.m4v?alt=media&token=d696d19e-08e9-49c9-b5b6-4880c07e2b33`, tags: ["Irene", "Michael", "Maui", "video"] },
  { id: 32, type: ProjectType.Video, title: `Space Oddity`, description: `To the tune of David Bowie's 'Space Oddity,' Stephen shares a glimpse of his life in apartment 14B-4.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fspace-oddity.webp?alt=media&token=45cdd83f-21ca-499c-8190-cb97a8459354`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftik-tok.m4v?alt=media&token=273476ee-4aa3-4569-9f77-3b894979f4a9`, tags: ["Stephen", "Manhattan", "video"] },
  { id: 33, type: ProjectType.Video, title: `Seasons of Love`, description: `16 years in the making...`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fseasons-of-love.webp?alt=media&token=432dbb22-c442-426e-bee5-3db15863ed8d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fseasons-of-love.m4v?alt=media&token=308e071c-af17-4a3d-a02b-ce73b4baddf8`, tags: ["Ben", "Emily", "Irene", "Michael", "Randi", "Glacier Bay National Park and Preserve", "video"] },
  { id: 34, type: ProjectType.Video, title: `Sea of Love`, description: `Exploring the 'American Alps.'`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsea-of-love.webp?alt=media&token=00e26245-0840-4b6b-a442-8a0650613b72`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fsea-of-love.m4v?alt=media&token=b951aa18-f18f-47d3-a550-324f921b4d96`, tags: ["Michael", "Glacier National Park", "video"] },
  { id: 35, type: ProjectType.Photo, title: `Yummy`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fyummy.webp?alt=media&token=703a46f7-42c2-41a1-88df-224aa290552a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fyummy.png?alt=media&token=2b06b472-b19a-4649-bc45-80c0b18439a7`, tags: ["image"] },
  { id: 36, type: ProjectType.Photo, title: `Bernal Hill Sunset w Sutro Tower`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-sutro.webp?alt=media&token=c60f4f4f-3507-47f2-8211-177b753f3d02`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-sutro.webp?alt=media&token=c60f4f4f-3507-47f2-8211-177b753f3d02`, tags: ["image"] },
  { id: 37, type: ProjectType.Photo, title: `San Bruno Sunrise`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsan-bruno-commute-sunrise.webp?alt=media&token=4bcf14f6-6f6a-4d6d-88e7-30c3af26c98a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fsan-bruno-commute-sunrise.png?alt=media&token=2e66208e-32d4-488b-9800-2639745fd008`, tags: ["image"] },
  { id: 38, type: ProjectType.Photo, title: `SF City Hall`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsf-city-hall.webp?alt=media&token=e433da4b-0991-41e3-98b9-24a31f93d1e9`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fsf-city-hall.png?alt=media&token=35c8500d-05b0-49e7-ae98-ae9dc5f829d3`, tags: ["image"] },
  { id: 39, type: ProjectType.Photo, title: `Bernal Hil Sunset`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset.webp?alt=media&token=6e7fb682-8c5f-4383-8dde-bd5ad217fa34`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset.webp?alt=media&token=6e7fb682-8c5f-4383-8dde-bd5ad217fa34`, tags: ["image"] },
  { id: 40, type: ProjectType.Photo, title: `Vatican Sunrise`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fvatican-sunrise.webp?alt=media&token=8c44af50-7dd8-422d-a3a9-a798d6272f07`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fvatican-sunrise.png?alt=media&token=71b52ddd-1a0b-4ebe-9742-0a3dc8860b5f`, tags: ["image"] },
  { id: 41, type: ProjectType.Photo, title: `Deb Cat Tree`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdeb-cat-tree-abstract.webp?alt=media&token=3b86b898-6289-4aa7-bbb8-941e847f6699`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdeb-cat-tree-abstract.png?alt=media&token=8ae0db13-8427-44d8-9c93-3f212d34989f`, tags: ["image"] },
  { id: 42, type: ProjectType.Photo, title: `Millie & Stephen`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fstephen-and-millie.webp?alt=media&token=e4b80f33-d179-45a3-b780-523a2d538428`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fstephen-and-millie.png?alt=media&token=e521f08e-5c8d-4f49-b6fe-e260d60e3918`, tags: ["image"] },
  { id: 43, type: ProjectType.Photo, title: `Dexter B&W`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdexter-b%26w.webp?alt=media&token=c23f5bee-9beb-4c08-aea9-e6c7c4f19c19`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdexter-b%26w.webp?alt=media&token=c23f5bee-9beb-4c08-aea9-e6c7c4f19c19`, tags: ["image"] },
  { id: 44, type: ProjectType.Photo, title: `Dexter on Ledge`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdexter-on-ledge.webp?alt=media&token=63d52b1d-134d-4ea9-95b5-c935cbc9275b`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdexter-on-ledge.png?alt=media&token=b67ac3a2-4c4e-4410-8bcd-b7272d77f973`, tags: ["image"] },
  { id: 45, type: ProjectType.Photo, title: `TSR Michael`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-michael-onelab.webp?alt=media&token=bad9df3f-a39a-49b9-b732-fd3396c658c0`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Ftsr-angles-michael.png?alt=media&token=e1e8b3a1-d056-4fa9-a328-83ddd9f998ab`, tags: ["image"] },
  { id: 46, type: ProjectType.Photo, title: `Yellow House SF`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fyellow-house-sf.webp?alt=media&token=c162a6d0-a19e-4896-a2df-0dc21002f080`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fyellow-house-sf.png?alt=media&token=2117bfd7-28c0-4f63-9941-c738d80b00c5`, tags: ["image"] },
  { id: 47, type: ProjectType.Photo, title: `Mission St Madrugada`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fmission-st-madrugada-abstract.webp?alt=media&token=817ca96d-4780-4610-b8dd-7fe99a3fcd6d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fmission-st-madrugada-abstract.png?alt=media&token=a6d686aa-4871-42ea-8dd6-c7b9d1621e43`, tags: ["image"] },
  { id: 48, type: ProjectType.Photo, title: `Granada Sunrise`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fgranada-sunrise.webp?alt=media&token=af425513-d8e9-49b0-b7fd-57df7b428190`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fgranada-sunrise.webp?alt=media&token=af425513-d8e9-49b0-b7fd-57df7b428190`, tags: ["image"] },
  { id: 49, type: ProjectType.Photo, title: `Bernal Hill Sunset Panorama`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-panorama.webp?alt=media&token=9cb7f173-884c-4d55-b4c9-08c696d4b296`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-panorama.webp?alt=media&token=9cb7f173-884c-4d55-b4c9-08c696d4b296`, tags: ["image"] },
  { id: 50, type: ProjectType.Photo, title: `Windmill Sunset Unedited`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fwindmill-sunset-unedited.webp?alt=media&token=b3c16f12-ee58-4b19-af3e-ac024724cba1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fwindmill-sunset-unedited.png?alt=media&token=c3517fc7-9ed5-4eb1-856c-70a271925d37`, tags: ["image"] },
  { id: 51, type: ProjectType.Photo, title: `Deb on Ledge`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdeb-on-ledge.webp?alt=media&token=a5f037bf-795b-4562-862f-04c9f0ff8d5e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdeb-on-ledge.png?alt=media&token=f7db5ed3-595a-427a-ac30-e1a21b7517d6`, tags: ["image"] },
  { id: 52, type: ProjectType.Photo, title: `TSR Angles`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-angles-michael.webp?alt=media&token=59f19a50-5075-42b0-80f7-49bfd54531f1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Ftsr-angles-michael.png?alt=media&token=e1e8b3a1-d056-4fa9-a328-83ddd9f998ab`, tags: ["image"] },
  { id: 53, type: ProjectType.Photo, title: `Windmill Sunset`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fwindmill-sunset.webp?alt=media&token=5974878e-9db0-4691-9653-d2320de573e7`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fwindmill-sunset.png?alt=media&token=536b494a-4425-43bc-94b8-44c47386a64d`, tags: ["image"] },
  { id: 54, type: ProjectType.Photo, title: `Deb Psychedelic`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdeb-psychedelic.webp?alt=media&token=08c6f226-45cc-4dae-a02c-47c158af44f6`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdeb-psychedelic.png?alt=media&token=173b336f-790d-448f-b104-435195c6720b`, tags: ["image"] },
  { id: 55, type: ProjectType.Photo, title: `Deb on Table`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdeb-on-table.webp?alt=media&token=772389f3-36ea-4aa3-b6c0-a07b815cc868`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdeb-on-table.png?alt=media&token=67ab3423-9cc8-4208-8fc2-b0df69a02aff`, tags: ["image"] },
  { id: 56, type: ProjectType.Photo, title: `Bernal Houses Sunset`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-houses-sunset.webp?alt=media&token=2ab0393f-8878-489d-98c7-3f1fd5b33485`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-houses-sunset.webp?alt=media&token=2ab0393f-8878-489d-98c7-3f1fd5b33485`, tags: ["image"] },
  { id: 57, type: ProjectType.Photo, title: `TSR Sunset Coast`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-sunet-coast.webp?alt=media&token=9c81f061-bda3-4e8c-ab3b-4b1fcc72dd8e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-sunet-coast.webp?alt=media&token=9c81f061-bda3-4e8c-ab3b-4b1fcc72dd8e`, tags: ["image"] },
  { id: 58, type: ProjectType.Photo, title: `Alaska Tranquil`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Falaska-tranquil.webp?alt=media&token=62042894-e58b-4912-82ca-1d9cb41ee7f0`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Falaska-tranquil.webp?alt=media&token=62042894-e58b-4912-82ca-1d9cb41ee7f0`, tags: ["image"] },
  { id: 59, type: ProjectType.Photo, title: `Bernal Twin Peaks`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-twin-peaks.webp?alt=media&token=fbd1caa0-8237-4eb4-bc3f-4d3a494fb5cb`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fbernal-twin-peaks.png?alt=media&token=c1f3607a-33a0-4acd-90d4-c6a07d6c85bd`, tags: ["image"] },
  { id: 60, type: ProjectType.Photo, title: `Dex is Coming`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdex-is-coming.webp?alt=media&token=8b7ab3a3-5c73-4c45-81d8-61a144954366`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdex-is-coming.png?alt=media&token=3a64662d-e838-43ad-b7b2-f882a2a4c49c`, tags: ["image"] },
  { id: 61, type: ProjectType.Photo, title: `Bernal Hill Panorama`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-panorama.webp?alt=media&token=a915e94a-e8d6-4e81-bd1b-109a17ad874f`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-panorama.webp?alt=media&token=a915e94a-e8d6-4e81-bd1b-109a17ad874f`, tags: ["image"] },
  { id: 62, type: ProjectType.Photo, title: `Bernal Houses`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-houses-sunset.webp?alt=media&token=2ab0393f-8878-489d-98c7-3f1fd5b33485`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fbernal-houses-sunset.png?alt=media&token=83b33377-9d36-489e-9588-90305399ad23`, tags: ["image"] },
  { id: 63, type: ProjectType.Photo, title: `Bernal Hill Steps`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-steps.webp?alt=media&token=1926bbeb-405c-4943-805f-4818bd5b6bc5`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-steps.webp?alt=media&token=1926bbeb-405c-4943-805f-4818bd5b6bc5`, tags: ["image"] },
  { id: 64, type: ProjectType.Photo, title: `Dex Psychedelic`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdex-psychedelic.webp?alt=media&token=2a1a93c6-cc05-42e8-b434-bda460f25484`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fdex-psychedelic.png?alt=media&token=b7b95512-1d26-4aec-8487-ff3c9cc8a83a`, tags: ["image"] },
  { id: 65, type: ProjectType.Photo, title: `Oregon Coast Forest`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Foregon-coast-forest.webp?alt=media&token=7ac9450a-f7d8-446b-be6f-eef35a39b0d4`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Foregon-coast-forest.png?alt=media&token=aa7477e6-b67e-4255-9b5e-902f0d761b24`, tags: ["image"] }
];

export const AI_SYSTEM_PROMPT = `You are the assistant for a personal creative portfolio website called Laundromatzat, showcasing videos, images, cinemagraphs, and interactive web apps built by the user. Your goals are:

- Help visitors explore featured projects, creative works, or tools.
- Answer questions about the creator’s interests or background.
- Route users to appropriate pages (e.g., /videos, /images, /cinemagraphs, /tools).
- Optionally run small AI-powered utilities (e.g., image captioning, random poem generator, etc).
- Provide suggestions for other projects the user could explore.

The tone should be warm, creative, and minimalist.

You are connected to a static React frontend and may receive inputs such as:
- User-selected route
- Chat prompts
- File uploads or text
- Project metadata (title, description, tags)

Reply in JSON if asked to return data for frontend (e.g., { title, description, link }).

Never break character. Always assume the user is visiting this portfolio and is curious, creative, or inspired.`;