
import { Project, ProjectType } from './types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    type: ProjectType.Photo,
    title: 'Neon Cityscape',
    description: 'A long-exposure shot capturing the vibrant light trails of a bustling city at night.',
    imageUrl: 'https://picsum.photos/seed/cityscape/800/600',
    tags: ['photography', 'city', 'long-exposure'],
  },
  {
    id: 2,
    type: ProjectType.Photo,
    title: 'Forest Whisper',
    description: 'Sunlight filtering through the canopy of a dense, ancient forest.',
    imageUrl: 'https://picsum.photos/seed/forest/800/600',
    tags: ['photography', 'nature', 'landscape'],
  },
  {
    id: 3,
    type: ProjectType.Video,
    title: 'Ocean\'s Breath',
    description: 'A short drone film showcasing the powerful and serene movement of ocean waves.',
    imageUrl: 'https://picsum.photos/seed/ocean/800/600',
    projectUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['videography', 'drone', 'nature'],
  },
  {
    id: 4,
    type: ProjectType.Tool,
    title: 'Color Palette Generator',
    description: 'An interactive tool to generate beautiful color palettes from an uploaded image.',
    imageUrl: 'https://picsum.photos/seed/palette/800/600',
    projectUrl: '#',
    tags: ['web-app', 'utility', 'design'],
  },
  {
    id: 5,
    type: ProjectType.Photo,
    title: 'Mountain Majesty',
    description: 'A breathtaking view from a mountain summit at sunrise.',
    imageUrl: 'https://picsum.photos/seed/mountain/800/600',
    tags: ['photography', 'landscape', 'adventure'],
  },
  {
    id: 6,
    type: ProjectType.Video,
    title: 'Stargazing Timelapse',
    description: 'A compilation of thousands of photos to show the movement of the stars across the night sky.',
    imageUrl: 'https://picsum.photos/seed/stars/800/600',
    projectUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['videography', 'timelapse', 'astronomy'],
  },
   {
    id: 7,
    type: ProjectType.Tool,
    title: 'Markdown Editor',
    description: 'A simple, real-time markdown editor with a live preview pane.',
    imageUrl: 'https://picsum.photos/seed/editor/800/600',
    projectUrl: '#',
    tags: ['web-app', 'utility', 'productivity'],
  },
  {
    id: 8,
    type: ProjectType.Photo,
    title: 'Desert Dunes',
    description: 'The shifting sands of a vast desert under the midday sun.',
    imageUrl: 'https://picsum.photos/seed/desert/800/600',
    tags: ['photography', 'landscape', 'travel'],
  },
  {
    id: 9,
    type: ProjectType.Cinemagraph,
    title: 'Endless Rinse Cycle',
    description: 'A mesmerizing loop of water splashing against a window, caught in a perpetual rinse.',
    imageUrl: 'https://picsum.photos/seed/rinse/800/600',
    tags: ['cinemagraph', 'loop', 'abstract'],
  },
  {
    id: 10,
    type: ProjectType.Cinemagraph,
    title: 'Lost Sock Portal',
    description: 'Where do they go? A swirling vortex of socks captured in a subtle, looping motion.',
    imageUrl: 'https://picsum.photos/seed/sock/800/600',
    tags: ['cinemagraph', 'surreal', 'humor'],
  },
];

