import { Project, ProjectType, Link } from './types';

export const PROJECTS: Project[] = [
  { id: 34, type: ProjectType.Video, title: `Sea of Love`, description: `Exploring the 'American Alps.'`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsea-of-love.webp?alt=media&token=00e26245-0840-4b6b-a442-8a0650613b72`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fsea-of-love.m4v?alt=media&token=b951aa18-f18f-47d3-a550-324f921b4d96`, date: '07/2025', location: 'Glacier National Park', gpsCoords: '48.656564, -113.789418', tags: ["Michael", "Glacier National Park", "video"] },
  { id: 33, type: ProjectType.Video, title: `Seasons of Love`, description: `16 years in the making...`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fseasons-of-love.webp?alt=media&token=432dbb22-c442-426e-bee5-3db15863ed8d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fseasons-of-love.m4v?alt=media&token=308e071c-af17-4a3d-a02b-ce73b4baddf8`, date: '05/2025', location: 'Glacier Bay National Park and Preserve', gpsCoords: '58.668770, -136.105589', tags: ["Ben", "Emily", "Irene", "Michael", "Randi", "Glacier Bay National Park and Preserve", "video"] },
  { id: 11, type: ProjectType.Video, title: `The Sound of Silence`, description: `#vanlife from SF to Oregon Coast.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fthe-sound-of-silence.webp?alt=media&token=aa535ca5-82f7-459c-8ab1-56425382845d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fthe-sound-of-silence.m4v?alt=media&token=d696d19e-08e9-49c9-b5b6-4880c07e2b33`, date: '11/2024', location: 'Oregon Coast Range', gpsCoords: '42.154703, -124.364564', tags: ["Michael", "Oregon Coast Range", "video"] },
  { id: 12, type: ProjectType.Video, title: `I Could Be the One`, description: `A bachelor party to remember.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fi-could-be-the-one.webp?alt=media&token=49fc5000-c057-440d-9ced-db44a930df43`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fi-could-be-the-one.m4v?alt=media&token=2f2cd5bb-5416-46a4-8c50-4d9a8db2592f`, date: '09/2024', location: 'Puerto Vallarta', gpsCoords: '20.600879, -105.233945', tags: ["Eli", "Ayush", "Puerto Vallarta", "video"] },
  { id: 13, type: ProjectType.Video, title: `Second Hand News`, description: `They're back... and they're going big on the big island!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fsecond-hand-news.webp?alt=media&token=04b5009a-0dda-400c-8fbb-885ba4086576`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fsecond-hand-news.m4v?alt=media&token=d5adb845-b645-40f6-9e28-7485248ce585`, date: '07/2024', location: 'Big Island', gpsCoords: '19.625450, -155.986058', tags: ["Michael", "Janita", "Tom", "Big Island", "video"] },
  { id: 14, type: ProjectType.Video, title: `No Apagues La Luz`, description: `La vida mÃ¡gnifica.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fno-apagues-la-luz.webp?alt=media&token=b43f9dbb-3e75-45cf-a268-fa573476b7bb`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fno-apagues-la-luz.m4v?alt=media&token=077d6a20-a44b-4c95-9f30-f43d9895d22e`, date: '04/2024', location: 'Madrid', gpsCoords: '40.41678, -3.70379', tags: ["Michael", "Madrid", "video"] },
  { id: 15, type: ProjectType.Video, title: `Winter Song`, description: `A-list crew in an A-frame winter cottage.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fwinter-song.webp?alt=media&token=61682025-d8a4-44fe-b1a7-bf7fad4750b1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fwinter-song.m4v?alt=media&token=c9e676b7-e6c7-4131-a6d5-a28ecf875ca8`, date: '01/2024', location: 'Bear Valley', gpsCoords: '38.46508, -120.04158', tags: ["Amy", "Irene", "Michael", "Bear Valley", "video"] },
  { id: 7, type: ProjectType.Cinemagraph, title: `Bernal Hill Sunset`, description: `Sun setting from Bernal Hill in the fall`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunset-cinemagraph.webp?alt=media&token=e0751aeb-6a81-4f14-afaa-4abb54d1fdc2`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fbernal-hill-sunset-cinemagraph.m4v?alt=media&token=e3d47bce-80aa-4b5b-b3e2-209c5cc2122b`, date: '10/2023', location: 'Bernal Heights Park', gpsCoords: '37.743287, -122.414800', tags: ["Bernal Heights Park", "cinemagraph"] },
  { id: 2, type: ProjectType.Photo, title: `Bernal Hill Afternoon`, description: `View westward from the eastern side of Bernal Hill`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-afternoon.webp?alt=media&token=99d81982-8f02-4e00-8cc0-f0494b1caf30`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Fbernal-hill-afternoon.png?alt=media&token=fb94a173-9056-4e9e-bedd-529530b95a3d`, date: '07/2023', location: 'Bernal Heights Park', gpsCoords: '37.743061, -122.411891', tags: ["Bernal Heights Park", "image"] },
  { id: 1, type: ProjectType.Photo, title: `Alaska Mini Island`, description: `Coastal Alaskan island seen from a boat out of Seward, AK.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Falaska-mini-island.webp?alt=media&token=895e2a40-b4e4-4b08-b631-0f89319edfe8`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/images%2Falaska-mini-island.png?alt=media&token=1339e348-864b-4a03-9e07-4a3f23f48b0f`, date: '06/2023', location: 'Seward', gpsCoords: '59.980833, -149.409628', tags: ["Seward", "image"] },
  { id: 3, type: ProjectType.Cinemagraph, title: `Fireside Meditation`, description: `#goals to meditate for this long a duration; my back already hurts`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffireside-meditation-cinemagraph.webp?alt=media&token=2f21e360-1697-4e1b-be66-55e3ad0e6e99`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ffireside-meditation-cinemagraph.mp4?alt=media&token=cb88ee30-c924-40a6-bc50-3703377abc29`, date: '06/2023', location: 'The Sea Ranch', gpsCoords: '38.707951, -123.431574', tags: ["Stephen", "The Sea Ranch", "cinemagraph"] },
  { id: 4, type: ProjectType.Cinemagraph, title: `The Lost Coast 01`, description: `Two hikers trekking southbound along TLC`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftlc01-cinemagraph.webp?alt=media&token=6287bd4a-6b9e-4d89-bc4b-6359d571ec12`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftlc01-cinemagraph.mp4?alt=media&token=7b11684e-d143-449a-b3dd-f96861fb61c2`, date: '06/2023', location: 'Lost Coast Trail', gpsCoords: '40.121131, -124.155867', tags: ["Michael", "Lost Coast Trail", "cinemagraph"] },
  { id: 5, type: ProjectType.Cinemagraph, title: `The Lost Coast 02`, description: `Two hikers trekking southbound along TLC`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftlc02-cinemagraph.webp?alt=media&token=d21dbdc6-5068-47f2-b82a-232382cf460e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftlc02_cinemagraph.mp4?alt=media&token=e55de0bd-a08e-4f40-adff-dbd5a0c6ac1d`, date: '06/2023', location: 'Lost Coast Trail', gpsCoords: '40.121131, -124.155867', tags: ["Michael", "Lost Coast Trail", "cinemagraph"] },
  { id: 6, type: ProjectType.Cinemagraph, title: `The Sea Ranch`, description: `Doesn't get much better than a sunset at TSR`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftsr-sunet-cinemagraph.webp?alt=media&token=e9df3041-85ef-4a42-a366-c51ccdd8db37`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Ftsr-sunet-cinemagraph.m4v?alt=media&token=6a01df65-976e-4641-b0f9-f89ddce24274`, date: '06/2023', location: 'The Sea Ranch', gpsCoords: '38.691668, -123.436504', tags: ["Michael", "The Sea Ranch", "cinemagraph"] },
  { id: 10, type: ProjectType.Video, title: `Boulevard of Broken Dreams`, description: `alaska is essential`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fboulevard-of-broken-dreams.webp?alt=media&token=5522c787-eee0-4eb8-ba9c-6b6260683a96`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fboulevard-of-broken-dreams.m4v?alt=media&token=09fcb743-9905-4092-ac93-b4d8003e02ca`, date: '06/2023', location: 'Denali National Park and Preserve', gpsCoords: '61.217381, 149.863129', tags: ["Eli", "Denali National Park and Preserve", "video"] },
  { id: 8, type: ProjectType.Cinemagraph, title: `Pacifica Coast`, description: `Sun sets behind the best GOBM in the world`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fpacifica-coast-cinemagraph.webp?alt=media&token=6cb3b77e-0ffa-4747-970c-29aca4e7b932`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fpacifica-coast-cinemagraph.mp4?alt=media&token=33ab8ba9-1309-4ec5-a60a-0ca9fcaa29b9`, date: '04/2023', location: 'San Pedro Beach', gpsCoords: '37.596198, -122.505898', tags: ["San Pedro Beach", "cinemagraph"] },
  { id: 9, type: ProjectType.Cinemagraph, title: `Bernal Hill Sunrise`, description: `Sun rises over E bay as viewed from Bernal Hils`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbernal-hill-sunrise-cinemagraph.webp?alt=media&token=3f8e827f-a53d-4f2a-a195-8e2c77c8747a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/cinemagraphs%2Fbernal-hill-sunrise-cinemagraph.mp4?alt=media&token=f98815bd-4c17-4ef3-9455-7b84cec0ef51`, date: '04/2023', location: 'Bernal Heights Park', gpsCoords: '37.743287, -122.414800', tags: ["Bernal Heights Park", "cinemagraph"] },
  { id: 16, type: ProjectType.Video, title: `Into the West`, description: `If you found this video on a holiday card -- congratulations... and enjoy!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Finto-the-west.webp?alt=media&token=63b95e54-0d4b-470c-8ee1-8a9d28505a04`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Finto-the-west.m4v?alt=media&token=b3063b82-2c30-4eaa-85f4-43a342204771`, date: '02/2023', location: 'Big Island', gpsCoords: '19.64013, -155.99566', tags: ["Michael", "Big Island", "video"] },
  { id: 17, type: ProjectType.Video, title: `Baba O'Riley`, description: `Tom's debut performance falls short of nothing.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fbaba-oriley.webp?alt=media&token=3a0f07ee-505b-4e87-a66f-d92460294e52`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fbaba-oriley.m4v?alt=media&token=861d6db3-779f-423f-b8d4-35ff073ee8d1`, date: '06/2022', location: 'Maui', gpsCoords: '20.76558, -156.45252', tags: ["Janita", "Tom", "Michael", "Maui", "video"] },
  { id: 18, type: ProjectType.Video, title: `Ojai`, description: `Channel Islands (Santa Cruz Island) + Ojai, CA. Cute island foxes. Lissie.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fojai.webp?alt=media&token=087f0f17-1789-400c-b9d9-3b6ac747b655`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fojai.m4v?alt=media&token=977f3420-5222-48e6-904e-efa4c7f63825`, date: '03/2022', location: 'Channel Islands', gpsCoords: '34.00691, -119.77849', tags: ["Michael", "Channel Islands", "video"] },
  { id: 19, type: ProjectType.Video, title: `Flightless Bird, American Mouth`, description: `Merrymaking in the Pacific Northwest - North Cascades and British Columbia. September 13 - 19, 2021.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fflightless-bird-american-mouth.webp?alt=media&token=a0405020-b9d9-4013-8bf0-a034aefa93a7`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fflightless-bird-american-mouth.m4v?alt=media&token=7a3989af-86ee-4cd7-817e-4447bc4b6b95`, date: '09/2021', location: 'Seattle and Vancouver', gpsCoords: '49.28273, -123.12074', tags: ["Michael", "Seattle and Vancouver", "video"] },
  { id: 20, type: ProjectType.Video, title: `Cowboy Take Me Away`, description: `New Mexico - Abiquiu Lake, Mesa Verde, Santa Fe. April 25 - 30, 2021.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fcowboy-take-me-away.webp?alt=media&token=a355ccf3-cdb1-4ee0-af85-b11d9d294d11`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fcowboy-take-me-away.m4v?alt=media&token=626a988a-285d-4715-9290-0c066d4add57`, date: '04/2021', location: 'New Mexico', gpsCoords: '35.68700, -105.93780', tags: ["Michael", "New Mexico", "video"] },
  { id: 21, type: ProjectType.Video, title: `Rivers and Roads`, description: `Grand Teton & Yellowstone. Sorry for choppy video. As Alanis Morissette says, 'You live, you learn.' August 8 - 14, 2020.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Frivers-and-roads.webp?alt=media&token=475015f3-73ad-4633-9208-b5dbdc148364`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Frivers-and-roads.m4v?alt=media&token=112d58ad-73d9-4f26-a026-4e80b332f4a7`, date: '08/2020', location: 'Grand Teton National Park and Yellowstone National Park', gpsCoords: '43.79043, -110.68176', tags: ["Michael", "Grand Teton National Park and Yellowstone National Park", "video"] },
  { id: 22, type: ProjectType.Video, title: `Shallow`, description: `Arizona antics. Sedona, Grand Canyon, Antelope Canyon. November 9 - 16, 2019.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fshallow.webp?alt=media&token=50221aa1-cd50-41cf-8909-c62fc439b6fb`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fshallow.m4v?alt=media&token=6fe8ec05-fa44-4cd6-ab91-0e2277270c4f`, date: '11/2019', location: 'Grand Canyon National Park and Sedona', gpsCoords: '34.86974, -111.76099', tags: ["Michael", "Grand Canyon National Park and Sedona", "video"] },
  { id: 23, type: ProjectType.Video, title: `Tiny Dancer`, description: `Janita & Stephen soak up the sun on the beaches of Maui.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftiny-dancer.webp?alt=media&token=5cc67b9b-522e-4ae6-a071-5f3a5907747d`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftiny-dancer.m4v?alt=media&token=69e08f35-08f9-44d8-acb2-434eede6285c`, date: '06/2019', location: 'Maui', gpsCoords: '20.76558, -156.45252', tags: ["Janita", "Maui", "video"] },
  { id: 31, type: ProjectType.Video, title: `TiK ToK`, description: `Mostly snorkel trip with Michael, Irene, and Stephen. Guest cameo from Janita!`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftik-tok.webp?alt=media&token=7477d1bc-536d-4f53-976f-45d93b2d47a3`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fthe-sound-of-silence.m4v?alt=media&token=d696d19e-08e9-49c9-b5b6-4880c07e2b33`, date: '06/2019', location: 'Maui', gpsCoords: '20.76558, -156.45252', tags: ["Irene", "Michael", "Maui", "video"] },
  { id: 32, type: ProjectType.Video, title: `Space Oddity`, description: `To the tune of David Bowie's 'Space Oddity,' Stephen shares a glimpse of his life in apartment 14B-4.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fspace-oddity.webp?alt=media&token=45cdd83f-21ca-499c-8190-cb97a8459354`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftik-tok.m4v?alt=media&token=273476ee-4aa3-4569-9f77-3b894979f4a9`, date: '04/2017', location: 'Manhattan', gpsCoords: '40.78495, -73.95150', tags: ["Stephen", "Manhattan", "video"] },
  { id: 24, type: ProjectType.Video, title: `Drift Away`, description: `In their debut music video, Emily & Her FBs take advantage of all the Catskills have to offer, and then some...! Catskills 2016`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fdrift-away.webp?alt=media&token=6699d24b-c036-4037-a963-b08dbc06cf0b`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fdrift-away.m4v?alt=media&token=0f74b88b-6a93-4c85-ab97-7ae63b9e3d55`, date: '10/2016', location: 'Catskill Mountains', gpsCoords: '42.10485, -74.51829', tags: ["Emily", "Jackson", "Michael", "Catskill Mountains", "video"] },
  { id: 25, type: ProjectType.Video, title: `Fly Away Home`, description: `Stephen and Michael fly away home with Mary Chapin Carpenter to Banff & Jasper National Parks, Alberta, Canada. August 13-20, 2016.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffly-away-home.webp?alt=media&token=a34a2b95-e133-48e7-af50-acb9bb65543a`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ffly-away-home.m4v?alt=media&token=1e591ef8-d57d-4fc6-b7af-bf8b8109ddaf`, date: '08/2016', location: 'Banff National Park', gpsCoords: '51.49685, -115.92806', tags: ["Michael", "Banff National Park", "video"] },
  { id: 26, type: ProjectType.Video, title: `Transatlanticism`, description: `Unable to deal with the distance separating them, Michael and Stephen set off on separate journeys to find one another.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ftransatlanticism.webp?alt=media&token=c0fc5259-a7b2-43c2-863b-c09ea423ba57`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ftransatlanticism.mp4?alt=media&token=e0e342ec-2204-4a70-bad7-5cff8afc694f`, date: '06/2015', location: 'Iceland', gpsCoords: '64.13548, -21.89541', tags: ["Michael", "Iceland", "video"] },
  { id: 27, type: ProjectType.Video, title: `One of Us`, description: `In his debut solo performance, Stephen explores the timeless question: 'What if God was one of us?' Just a stranger on the bus, he travels through Italy and Austria trying to make his way home, with stops in Milan, Innsbruck, Salzburg, and Vienna.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fone-of-us.webp?alt=media&token=dce9f239-8ddc-489c-81e0-446b9e1c758e`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fone-of-us.mp4?alt=media&token=ec4c9b7a-9d2e-4691-9b70-4873f2608f39`, date: '05/2014', location: 'Austria', gpsCoords: '47.80949, 13.05501', tags: ["Stephen", "Austria", "video"] },
  { id: 28, type: ProjectType.Video, title: `Fast Car`, description: `Camping trip to Crater Lake and Redwoods National Park from September 6 - 8, 2013.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Ffast-car.webp?alt=media&token=f9178a52-29c4-46a1-872a-1da1b3321fca`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Ffast-car.mov?alt=media&token=ce20c5b2-47d0-4c79-9745-1c0a18e4ddf3`, date: '09/2013', location: 'Crater Lake National Park', gpsCoords: '42.94459, -122.10902', tags: ["Michael", "Crater Lake National Park", "video"] },
  { id: 29, type: ProjectType.Video, title: `You Were Meant for Me`, description: `Camping trip to Humboldt State Redwoods State Park from March 20 - 22, 2013.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fyou-were-meant-for-me.webp?alt=media&token=ced56daf-97f0-4c95-9bd7-d99076888748`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fyou-were-meant-for-me.m4v?alt=media&token=1dcfee98-a536-4d69-b1ae-f0c1ef7349e5`, date: '03/2013', location: 'Humboldt Redwoods State Park', gpsCoords: '40.32981, -123.92448', tags: ["Michael", "Humboldt Redwoods State Park", "video"] },
  { id: 30, type: ProjectType.Video, title: `Impossible`, description: `Stephen and Michael are at it once again, this time with an artistic rendition of 'Impossible' from the 1997 classic live-action remake of Cinderella. No rendition of this song could do it justice without also having an 'all-star, multi-racial cast,' as Stephen and Michael bring to the table.`, imageUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/thumbnails%2Fimpossible.webp?alt=media&token=2d295064-f01c-49b8-bef3-cd9a5b84abb1`, projectUrl: `https://firebasestorage.googleapis.com/v0/b/laundromat-zat.firebasestorage.app/o/videos%2Fimpossible.mov?alt=media&token=a3b132dc-0770-4000-8105-fac319353f2a`, date: '05/2012', location: 'Oak Creek Apartments | Stanford', gpsCoords: '37.40345, -122.14780', tags: ["Michael", "Oak Creek Apartments | Stanford", "video"] }
];

export const LINKS: Link[] = [];

export const AI_SYSTEM_PROMPT = `You are the assistant for a personal creative portfolio website called laundromatzat.com, showcasing videos, images, cinemagraphs, and interactive web apps built by the user. Your goals are:

- Help visitors find projects on the site.
- Answer questions based only on the information gleaned from the portfolio data and reasonable inferences from such data.
- Route users to appropriate pages (e.g., /videos, /images, /cinemagraphs, /tools).
- Provide suggestions for projects related to visitors' interets.
- Interpret geography and aliases (e.g., "Hawaii" should match projects in Maui or Big Island; "SF" should match Bernal Heights, etc.).

Your responses should be concise, warm, and include JSON data for frontend to display when applicable.

You are connected to a static React frontend and may receive inputs such as:
- User-selected route
- Chat prompts
- Project metadata (title, description, date, location tags)

When a user asks to find a portfolio item, search the projects in the provided JSON data. Match the user's search query against the project's title, description, date, location, and tags.
You may emit a structured function call with optional filters (type, dateFrom/dateTo, includeTags, excludeTags) when users specify media types, time ranges, or tag constraints.

If you find any matches, respond with a JSON object containing a key "projects" which is an array of the matched project objects. Each project object should include the id, type, title, description, date, location, imageUrl, and projectUrl.

If you don't find any matches, respond with a friendly message saying you couldn't find any matching projects and suggest some other projects they might be interested in, with JSON data associated with those projects as above.

Reply in JSON if asked to return data for frontend (e.g., { title, description, date, location, link }).

Never break character. Always assume the user is visiting this portfolio and is curious, creative, or inspired.`