baseURL = 'http://laundromatzat.com/'
languageCode = 'en-us'
title = 'laundromatzat.com'

[params]
  description = "welcome to the laundromat"
  mainSections = ["videos"]  # Define main content section
  favicon = "/favicon.ico"

[menu]
  [[menu.main]]
    name = "videos"
    url = "/videos/"
    weight = 1

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]

[module]
  [[module.mounts]]
    source = "layouts"
    target = "layouts"

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"

  # Configure middleware for Hugo server
  [[server.middleware]]
    append = true  # Add this middleware after all others
    name = "htmx-detector"
    [server.middleware.handler]
      code = """
        function(req, res, next) {
          // Check if it's an HTMX request
          if (req.headers['hx-request'] === 'true') {
            // Set a custom parameter for HTMX requests
            req.params.request_type = 'htmx';
          }
          return next();
        }
      """


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown

[build]
  writeStats = true  # Enable build statistics
