import React from "react";
import {
  Unit,
  generateCarvingPlan,
  generateCarvingVariations,
} from "@/services/woodCarvingService";
import {
  saveProject,
  updateProject,
  type WoodCarvingProject,
} from "@/services/woodCarvingApi";
import { AuraButton } from "@/components/aura";
import { DesignGallery, SortOption } from "@/components/DesignGallery";
import { ClockIcon } from "@heroicons/react/24/outline";
import { RefreshCw, Wand2, Ruler } from "lucide-react";

// Components
import DesignInputForm from "./components/DesignInputForm";
import StyleSelector from "./components/StyleSelector";
import BlueprintViewer from "./components/BlueprintViewer";
import { useWoodCarvingProject } from "./hooks/useWoodCarvingProject";

const EXAMPLE_DESCRIPTIONS = [
  "A majestic eagle landing on a branch, realistic style",
  "Geometric low-poly bear head",
  "Celtic knot pattern on a walking stick handle",
  "Art Nouveau floral relief panel",
];

const WoodCarvingVisualizerPage: React.FC = () => {
  const {
    description,
    userNotes,
    variations,
    selectedVariation,
    designData,
    carvingSteps,
    unit,
    phase,
    activeTab,
    isRefining,
    refinementNote,
    currentStep,
    completedSteps,
    projectId,
    isLoading,
    error,
    setPhase,
    setDescription,
    setUserNotes,
    setVariations,
    selectVariation,
    setDesignData,
    setCarvingSteps,
    setActiveTab,
    toggleUnit,
    setIsRefining,
    setRefinementNote,
    completeStep,
    goToStep,
    setProjectId,
    resetProject,
    setIsLoading,
    setError,
  } = useWoodCarvingProject();

  const [isGalleryOpen, setIsGalleryOpen] = React.useState(false);

  // Generate variations
  const handleGenerateVariations = async () => {
    if (!description.trim()) return;

    setPhase(1);
    setError(null);
    setVariations([]);

    try {
      const results = await generateCarvingVariations(description);
      setVariations(results);
      setPhase(2);
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to generate variations. Please try again.",
      );
      setPhase(0);
    }
  };

  // Generate blueprint
  const handleGenerateBlueprint = async () => {
    if (!selectedVariation) return;

    setPhase(3);
    setError(null);

    try {
      const finalPrompt = userNotes
        ? `${description}. Notes: ${userNotes}`
        : description;

      const plan = await generateCarvingPlan(
        finalPrompt,
        selectedVariation.imageUrl,
      );
      setDesignData(plan);
      setPhase(4);
      setActiveTab("concept");

      // Save to backend
      try {
        if (projectId) {
          await updateProject(projectId, {
            description,
            variations,
            selectedVariation,
            blueprint: plan,
          });
        } else {
          const savedProject = await saveProject({
            description,
            variations,
            selectedVariation,
            blueprint: plan,
          });
          setProjectId(savedProject.id);
        }
      } catch (err) {
        console.error("Failed to save project:", err);
      }
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to generate blueprint. Please try again.",
      );
      setPhase(2);
    }
  };

  // Regenerate after annotation
  const handleRegenerateDesign = async (annotatedImageBase64: string) => {
    const refinePrompt = refinementNote
      ? `Refine this design based on the visual markups (red/green/blue lines) and these notes: ${refinementNote}. Original subject: ${description}`
      : `Refine this design based on the visual markups. Original subject: ${description}`;

    setPhase(3);
    setIsRefining(false);
    setDesignData(null!);

    try {
      const newPlan = await generateCarvingPlan(
        refinePrompt,
        annotatedImageBase64,
      );
      setDesignData(newPlan);
      setPhase(4);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to refine design");
      setPhase(4);
    }
  };

  // Download results
  const handleDownloadResults = () => {
    if (!designData) return;

    const markdownContent = `# Wood Carving Project: ${description}

## Selected Style: ${selectedVariation?.name}
${selectedVariation?.description}

## Carving Strategy
${designData.guideText}

---
*Generated by laundromatzat Wood Carving Visualizer*
`;

    const guideBlob = new Blob([markdownContent], { type: "text/markdown" });
    const guideUrl = URL.createObjectURL(guideBlob);
    const guideLink = document.createElement("a");
    guideLink.href = guideUrl;
    guideLink.download = `${description.slice(0, 20).replace(/\s+/g, "-")}-strategy.md`;
    document.body.appendChild(guideLink);
    guideLink.click();
    document.body.removeChild(guideLink);
    URL.revokeObjectURL(guideUrl);

    const downloadImage = (dataUrl: string, fileName: string) => {
      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    };

    downloadImage(
      designData.conceptUrl,
      `${description.slice(0, 20).replace(/\s+/g, "-")}-concept.png`,
    );
    downloadImage(
      designData.schematicUrl,
      `${description.slice(0, 20).replace(/\s+/g, "-")}-blueprint.png`,
    );
  };

  const sortOptions: SortOption[] = [
    {
      label: "Newest First",
      value: "date-desc",
      compareFn: (a: unknown, b: unknown) => {
        const aDate = new Date((a as WoodCarvingProject).createdAt).getTime();
        const bDate = new Date((b as WoodCarvingProject).createdAt).getTime();
        return bDate - aDate;
      },
    },
    {
      label: "Oldest First",
      value: "date-asc",
      compareFn: (a: unknown, b: unknown) => {
        const aDate = new Date((a as WoodCarvingProject).createdAt).getTime();
        const bDate = new Date((b as WoodCarvingProject).createdAt).getTime();
        return aDate - bDate;
      },
    },
  ];

  return (
    <div className="min-h-screen bg-aura-bg text-aura-text-primary font-sans selection:bg-aura-accent selection:text-white pb-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-6">
          <div>
            <h1 className="text-4xl md:text-5xl font-serif font-light text-aura-text-primary mb-2">
              Wood Carving <span className="text-aura-accent">Visualizer</span>
            </h1>
            <p className="text-aura-text-secondary text-lg font-light max-w-2xl">
              From concept to cut list. Generate styles, select your favorite,
              and get a technical blueprint.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsGalleryOpen(true)}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-white hover:bg-aura-surface text-aura-text-secondary hover:text-aura-text-primary rounded-full shadow-aura-sm hover:shadow-aura-md aura-transition"
            >
              <ClockIcon className="w-5 h-5" />
              <span className="font-medium">History</span>
            </button>
            {phase > 0 && (
              <AuraButton
                variant="secondary"
                size="sm"
                onClick={resetProject}
                icon={<RefreshCw className="w-4 h-4" />}
              >
                Start New Project
              </AuraButton>
            )}
          </div>
        </div>

        {/* Error Banner */}
        {error && (
          <div className="bg-red-900/20 border border-red-500/50 text-red-200 p-4 rounded-xl mb-8 flex items-start gap-3">
            <div className="mt-1">
              <Wand2 className="w-5 h-5 text-red-400" />
            </div>
            <p>{error}</p>
          </div>
        )}

        {/* PHASE 0: INPUT */}
        {phase === 0 && (
          <DesignInputForm
            description={description}
            onDescriptionChange={setDescription}
            onSubmit={handleGenerateVariations}
            isLoading={isLoading}
            exampleDescriptions={EXAMPLE_DESCRIPTIONS}
            onOpenGallery={() => setIsGalleryOpen(true)}
          />
        )}

        {/* PHASE 1: GENERATING VARIATIONS */}
        {phase === 1 && (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="relative w-24 h-24 mb-8">
              <div className="absolute inset-0 border-4 border-white/10 rounded-full" />
              <div className="absolute inset-0 border-4 border-aura-accent rounded-full border-t-transparent animate-spin" />
              <Wand2 className="absolute inset-0 m-auto w-8 h-8 text-aura-accent animate-pulse" />
            </div>
            <h3 className="text-2xl font-light text-white mb-2">
              Imagining Possibilities...
            </h3>
            <p className="text-zinc-500">
              Our AI is sketching 4 distinct variations of "{description}"
            </p>
          </div>
        )}

        {/* PHASE 2: SELECT VARIATION */}
        {phase === 2 && (
          <StyleSelector
            variations={variations}
            selectedVariation={selectedVariation}
            onSelectVariation={selectVariation}
            userNotes={userNotes}
            onUserNotesChange={setUserNotes}
            onGenerateBlueprint={handleGenerateBlueprint}
            isLoading={isLoading}
          />
        )}

        {/* PHASE 3: GENERATING BLUEPRINT */}
        {phase === 3 && (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="relative w-32 h-32 mb-8">
              <div className="absolute inset-0 border-4 border-zinc-700/30 rounded-full animate-ping" />
              <div className="absolute inset-4 border-2 border-aura-accent rounded-full opacity-50" />
              <div className="absolute inset-0 flex items-center justify-center">
                <Ruler className="w-12 h-12 text-aura-accent animate-bounce" />
              </div>
            </div>
            <h3 className="text-3xl font-light text-white mb-2">
              Analyzing Geometry...
            </h3>
            <p className="text-zinc-400 max-w-md mx-auto">
              We are converting the <b>{selectedVariation?.name}</b> concept
              into a technical orthographic projection and cutting strategy.
            </p>
          </div>
        )}

        {/* PHASE 4: BLUEPRINT VIEWER */}
        {phase === 4 && designData && (
          <BlueprintViewer
            designData={designData}
            carvingSteps={carvingSteps}
            currentStep={currentStep}
            completedSteps={completedSteps}
            unit={unit}
            description={description}
            variationName={selectedVariation?.name || ""}
            activeTab={activeTab}
            isRefining={isRefining}
            refinementNote={refinementNote}
            onTabChange={setActiveTab}
            onToggleUnit={toggleUnit}
            onExitBlueprint={() => setPhase(2)}
            onDownloadResults={handleDownloadResults}
            onStartRefining={() => setIsRefining(true)}
            onCancelRefining={() => setIsRefining(false)}
            onRefinementNoteChange={setRefinementNote}
            onRegenerateDesign={handleRegenerateDesign}
            onCompleteStep={completeStep}
            onGoToStep={goToStep}
          />
        )}
      </div>

      <style>{`
        .animate-fade-in-up { animation: fadeInUp 0.6s ease-out forwards; }
        @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        
        .animate-slide-up { animation: slideUp 0.4s ease-out forwards; }
        @keyframes slideUp { from { transform: translateY(100%); } to { transform: translateY(0); } }
      `}</style>

      {/* Design Gallery */}
      <DesignGallery
        title="Carving Project History"
        fetchEndpoint="/api/wood-carving/projects"
        isOpen={isGalleryOpen}
        onClose={() => setIsGalleryOpen(false)}
        onLoad={(item: WoodCarvingProject) => {
          setDescription(item.description);
          setVariations(item.variations || []);
          selectVariation(item.selectedVariation || null!);
          setDesignData(item.blueprint || null!);
          setProjectId(item.id);
          if (item.blueprint) setPhase(4);
          else if (item.selectedVariation) setPhase(2);
          else if (item.variations && item.variations.length > 0) setPhase(2);
          else setPhase(0);
          setIsGalleryOpen(false);
        }}
        deleteEndpoint="/api/wood-carving/projects"
        emptyMessage="No projects found. Start a new project to begin."
        sortOptions={sortOptions}
        renderPreview={(item: WoodCarvingProject) => (
          <div className="flex flex-col gap-6 h-full">
            <div className="bg-slate-900 rounded-xl p-6 border border-slate-800">
              <h3 className="text-lg font-semibold text-white mb-4">
                Project Description
              </h3>
              <p className="text-slate-300">{item.description}</p>
            </div>
            {item.selectedVariation && (
              <div className="bg-slate-900 rounded-xl p-6 border border-slate-800">
                <h3 className="text-lg font-semibold text-white mb-4">
                  Selected: {item.selectedVariation.name}
                </h3>
                <img
                  src={item.selectedVariation.imageUrl}
                  alt={item.selectedVariation.name}
                  className="w-full h-auto rounded-lg"
                />
              </div>
            )}
            {item.blueprint && (
              <div className="bg-slate-900 rounded-xl p-6 border border-slate-800">
                <h3 className="text-lg font-semibold text-white mb-4">
                  Blueprint
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  <img
                    src={item.blueprint.conceptUrl}
                    alt="Concept"
                    className="w-full h-auto rounded-lg"
                  />
                  <img
                    src={item.blueprint.schematicUrl}
                    alt="Schematic"
                    className="w-full h-auto rounded-lg"
                  />
                </div>
              </div>
            )}
          </div>
        )}
        renderItem={(item: WoodCarvingProject) => (
          <div className="flex flex-col h-full bg-white border border-slate-200 rounded-lg overflow-hidden hover:border-blue-400 transition-colors cursor-pointer group">
            <div className="p-4 bg-gradient-to-br from-amber-50 to-orange-50 border-b border-slate-200">
              <p className="text-sm font-semibold text-slate-900 line-clamp-2">
                {item.description}
              </p>
              <p className="text-xs text-slate-500 mt-1">
                {new Date(item.createdAt).toLocaleDateString()}
              </p>
            </div>
            <div className="flex-1 p-4">
              {item.selectedVariation ? (
                <div>
                  <img
                    src={item.selectedVariation.imageUrl}
                    alt={item.selectedVariation.name}
                    className="w-full h-32 object-cover rounded border border-slate-200"
                  />
                  <p className="text-xs text-slate-600 mt-2 font-medium">
                    {item.selectedVariation.name}
                  </p>
                  {item.blueprint && (
                    <p className="text-xs text-green-600 mt-1">
                      ✓ Blueprint ready
                    </p>
                  )}
                </div>
              ) : (
                <div className="flex items-center justify-center h-32 bg-slate-100 rounded border border-slate-200">
                  <p className="text-xs text-slate-500">
                    No variation selected
                  </p>
                </div>
              )}
            </div>
          </div>
        )}
      />
    </div>
  );
};

export default WoodCarvingVisualizerPage;
