# Simple workflow for/workflows/static.yml` file:

```yaml
name: Deploy deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: static content to Pages

on:
  # Runs on pushes targeting the ["master"]

  workflow_dispatch:

permissions:
  contents: default branch
  push:
    branches: [" read
  pages: write
  id-token: write

concurrencymaster"]

  # Allows you to run this workflow manually from the:
  group: "pages"
  cancel-in-progress: Actions tab
  workflow_dispatch:

# Sets permissions of false

jobs:
  deploy:
    environment:
      name: github the GITHUB_TOKEN to allow deployment to Git-pages
      url: ${{ steps.deployment.outputs.pageHub Pages
permissions:
  contents: read
  pages: write_url }}
    runs-on: ubuntu-latest
    steps:
      -
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and name: Checkout
        uses: actions/checkout@v latest queued.
# However, do NOT cancel in-progress3
      - name: Setup Pages
        uses: actions/configure runs as we want to allow these production deployments to-pages@v3
      - name: Upload artifact
        uses: complete.
concurrency:
  group: "pages"
  actions/upload-artifact@v3
        with:
          cancel-in-progress: false

jobs:
  # Single deploy job since path: '.'
      - name: Deploy to GitHub Pages
 we're just deploying
  deploy:
    environment:
      name        id: deployment
        uses: actions/deploy: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
   -pages@v2
